### ISSUE TITLE
Need to submit to the official Arduino library list

### ISSUE THREAD

**Issue by joshgoebel** [Arduboy/ArduboyPlayTune#2]
@rogosher You want to help with this?

**Comment by MLXXXp** [comment]
The library.properties file is up to date, and a tagged release has been created to match. I think all that's required now is to submit the request.

**Comment by joshgoebel** [comment]
Is playtunres ALREADY on the list then?

**Comment by joshgoebel** [comment]
If not you ahve to manually request it be added initially before they even watch for updates.

**Comment by MLXXXp** [comment]
As I said above, I think everything is ready to go but no one has yet requested that it be added. This is done by opening an issue on Arduino's GitHub
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

@rogosher did it for the Arduboy library. I haven't pressed the matter because there hasn't been a released library for the Arduboy that can use ArduboyPlaytune, until [Arduboy2](https://github.com/MLXXXp/Arduboy2), which I released yesterday (but is still kind of in flux).

**Comment by joshgoebel** [comment]
Really, why can't any library use it?  Not that that was the intent - just asking.

**Comment by MLXXXp** [comment]
Actually, it **was** my intent that projects other than Arduboy can use it. That's why I didn't do things like hard coding the speaker pin numbers. I discussed this in the comment for the PR: https://github.com/Arduboy/ArduboyPlaytune/pull/6#issue-159235361

So yes, for this reason it could be submitted immediately. I just thought it might be good to wait and see if _Arduboy2_ and/or _ArduboyTones_ are accepted and made official under the Arduboy account, and then submit them all at the same time.

However, it's fine with me if someone wants to make the request now.

**Comment by MLXXXp** [comment]
Forgot to close this. ArduboyPlaytune was added to the Library Manager in December, 2016.
