### ISSUE TITLE
OK to change license from GPL to MIT?

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/ArduboyPlayTune#7]
@LenShustek, @Arduboy, @rogosher, @yyyc514,

The original [arduino-playtune](https://github.com/LenShustek/arduino-playtune) library, that this ArduboyPlaytune library is based on, has recently had its license changed from GPL V3 to MIT.

In regards to this, does anyone object to changing this library's license to MIT to match?

**Comment by LenShustek** [comment]
I changed to the MIT license because it is more permissive: it allows the code to be used in potentially commercial applications without requiring all the code using it to also be distributed as open source. I certainly have no objection to derivative libraries changing to the MIT license. It's the better choice if your objective is to maximize the use of your code.

**Comment by MLXXXp** [comment]
License changed to MIT.
